version: "3.8"
services:
  data-model-mapper-gui:
    image: https://github.com/opsilab/data-model-mapper.git#frontend
    build:
      context: frontend
      dockerfile: ./frontend/Dockerfile
      args:
        BASE_HREF: /data-model-mapper-gui/
    ports:
      - "12345:80"
    volumes:
      - ./src/assets/config.json:/usr/share/nginx/html/assets/config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cape-network
  data-model-mapper:
    image: https://github.com/opsilab/data-model-mapper.git#frontend
    build: 
      context: backend
      dockerfile: ./backend/Dockerfile
    container_name: data_model_mapper
    depends_on:
      - db     
    ports:
     - 5500:5500
    restart: always
  db:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    restart: unless-stopped

volumes:
  db_data:

networks:
 cape-network:
   name: data-model-mapper-gui-network
   driver: bridge
   driver_opts:
     com.docker.network.driver.mtu: 1400
