version: '3'
 
services:
  minio:
    image: minio/minio
    #restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    #volumes:
    #  - ./minio-storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: BeOp3nPassword
      #MINIO_BROWSER_REDIRECT_URL: http://localhost:9001/minio/
      MINIO_IDENTITY_OPENID_CONFIG_URL: https://platform.beopen-dep.it/auth/realms/master/.well-known/openid-configuration
      MINIO_BROWSER_REDIRECT_URL: 'http://host.docker.internal:9001'
      MINIO_IDENTITY_OPENID_CLIENT_ID: minio-app
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: W9qhXVr3iou2ry6YIOSlQIHpBTtd1KUb
      MINIO_IDENTITY_OPENID_SCOPES: 'openid profile email'
      MINIO_IDENTITY_OPENID_CLAIM_NAME: policy
      MINIO_IDENTITY_OPENID_REDIRECT_URI: http://host.docker.internal:9001/oauth_callback
    command: server --console-address ":9001" /data

volumes:
  minio-storage: {}