name: Build Backend

on:
  push:
    branches:
      - frontend_dev
      - frontend
    paths:
      - 'backend/**'
      - 'server'
    #  - '.github/**'
  pull_request:
    branches:
      - frontend_dev
      - frontend
    paths:
        - 'backend/**'
        - 'server'
    #    - '.github/**'

jobs:

  build-backend:
            runs-on: ubuntu-latest
        
            steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
        
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./server
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/data-model-mapper-backend:latest
